server:
  port: 8762

spring:
  application:
    name: service-david

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    ## 心跳时间 续约间隔时间(缺省值为30s)
    lease-renewal-interval-in-seconds: 30
    ## 发呆时间，服务续约到期时间(缺省值为90s)
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

