#spring:
#  application:
#    name: config-client

#  cloud:
#    config:
#      label: master
#      name: application
#      profile: fat
#      enabled: true
#      uri: http://localhost:8768
#      username: m15291092760@163.com
#      password: Li691212


server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}