server:
  port: 8767

spring:
  application:
    name: service-zuul

zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    api-feign:
      path: /api-feign/**
      serviceId: service-feign

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true