server:
  port: 8768



spring:
  application:
    name: config-server
  cloud:
    config:
      label: david-dev
      server:
        git:
          uri: https://github.com/equalsTrue/SpringCloudConfig.git
          username: m15291092760@163.com
          password: Li691212
          search-paths: springcloudConfig

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
